"""change dim to 384

Revision ID: 1493296b9b73
Revises: 3806b678f86e
Create Date: 2026-02-25 15:49:51.002089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1493296b9b73'
down_revision: Union[str, Sequence[str], None] = '3806b678f86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documents ALTER COLUMN embedding TYPE vector(384);")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documents ALTER COLUMN embedding TYPE vector(384);")
    # ### end Alembic commands ###
