"""chnaged the embedding size to 768

Revision ID: 3806b678f86e
Revises: d1c4074173c7
Create Date: 2026-02-20 17:47:00.578625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3806b678f86e'
down_revision: Union[str, Sequence[str], None] = 'd1c4074173c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documents ALTER COLUMN embedding TYPE vector(768);")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documents ALTER COLUMN embedding TYPE vector(1536);")
    # ### end Alembic commands ###
